// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"SRD_AltMenuScreen_Mobile","status":true,"description":"Alternative Menu Screen: makes the commands bigger and easier to press on mobile devices.","parameters":{"\"Leave Menu\" Command":"true","\"Leave Menu\" Name":"Cerrar Menu","Command Font":"Gamefont","Command Font Size":"36","== Minor Positions ==":"","Face Padding":"2","Face X":"2","Face Y":"2","Max Status Rows":"1","Max Status Cols":"1","Command Columns":"3","Command Rows":"3"}},
{"name":"YEP_RegionRestrictions","status":true,"description":"v1.04 Use regions to block out Events and/or the player from\nbeing able to venture into those spots.","parameters":{"Player Restrict":"1","Event Restrict":"0","All Restrict":"0","Player Allow":"2","Event Allow":"0","All Allow":"0"}},
{"name":"GALV_MessageSoundEffects","status":true,"description":"Play sound effects when during Show Text event commands.","parameters":{"Delay Time":"10","Default Talk SE":"Cursor1,80,150","Default Confirm SE":"","-----------":"","Quick SE 1":"","Quick SE 2":"","Quick SE 3":"","Quick SE 4":""}},
{"name":"MadeWithMv","status":true,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"Aerosoles-fuera","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}}
];
